FROM arm64v8/alpine:3.22@sha256:d7641d4e055534bdac03070d3223d064999a9f2296598ec5122b66ceec18887b

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-skip-pipeline"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-skip-pipeline"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-skip-pipeline"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-skip-pipeline"

ADD release/linux/arm64/drone-skip-pipeline /bin/
ENTRYPOINT ["/bin/drone-skip-pipeline"]
