FROM arm64v8/alpine:3.24@sha256:7669ab567680cf2bca3130a407e430cc4f08e42328e5ad7305f86a4849accf18

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-skip-pipeline"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-skip-pipeline"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-skip-pipeline"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-skip-pipeline"

ADD release/linux/arm64/drone-skip-pipeline /bin/
ENTRYPOINT ["/bin/drone-skip-pipeline"]
