FROM arm32v7/alpine:3.15@sha256:5b86708e3b4d1f78c9f5252bd1713365c53f8ac84a101a647441861960d16682

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-skip-pipeline"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-skip-pipeline"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-skip-pipeline"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-skip-pipeline"

ADD release/linux/arm/drone-skip-pipeline /bin/
ENTRYPOINT ["/bin/drone-skip-pipeline"]
