FROM arm32v7/alpine:3.14@sha256:e12ff876f0075740ed3d7bdf788107ae84c1b3dd6dc98b3baea41088aba5236f

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-skip-pipeline"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-skip-pipeline"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-skip-pipeline"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-skip-pipeline"

ADD release/linux/arm/drone-skip-pipeline /bin/
ENTRYPOINT ["/bin/drone-skip-pipeline"]
