FROM alpine:3.19@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-skip-pipeline"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-skip-pipeline"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-skip-pipeline"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-skip-pipeline"

ADD release/linux/amd64/drone-skip-pipeline /bin/
ENTRYPOINT ["/bin/drone-skip-pipeline"]
